name: GitHub Secrets

on:
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
            echo "SUPER_SECRET_TECH: ${{ secrets.SUPER_SECRET_TECH  }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"

      - name: Print Secret as an environment variable
        run: |
            echo "SUPER_SECRET_TECH: $SUPER_SECRET_TECH"
        env:
            SUPER_SECRET_TECH: ${{ secrets.SUPER_SECRET_TECH }}